version: '3.4'

networks:
  ysc-net:
    external:
      name: ysc-net
services:
  nginx:
    image: nginx:1.19.2-alpine
    container_name: reverse-proxy-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ysc-net
    ports:
      - 80:80
    depends_on:
      - chessserver
      - middleware
      - stockfishserver
      - chessclient
      - ystemandchess
  chessserver:
    image: chessserver
    container_name: chessserver
    environment:
      - PORT=3000
    networks:
      - ysc-net
    expose:
      - "3000"
    volumes:
      - ./chessServer:/usr/src/app
  chessclient:
    image: chessclient
    container_name: chessclient
    environment:
      - PARENT=ystemandchess
    networks:
      - ysc-net
    expose:
      - "80"
    volumes:
      - ./chessClient:/usr/share/nginx/html
  stockfishserver:
    image: stockfishserver
    container_name: stockfishserver
    environment:
      - PORT=8080
    networks:
      - ysc-net
    expose:
      - "8080"
    volumes:
      - ./stockfishserver:/usr/src/app
  middleware:
    image: middleware
    container_name: middleware
    environment:
      - indexKey=4F15D94B7A5CF347A36FC1D85A3B487D8B4F596FB62C51EFF9E518E433EA4C8C
      - key=AKIA3W5HAAMIUEL5K4OK
      - secret=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
      - appID=6c368b93b82a4b3e9fb8e57da830f2a4
      - mongocredentials="mongodb+srv://useradmin:uumrcvqtyplpq1hi@cluster0-rxbrl.mongodb.net/test?retryWrites=true&w=majority"
      - auth="Basic OTE3ZTZlOTlmODgxNDEwYWI2ZjEyNmY3ZTJiMWM5MDc6NWYwMTU0MTIwMmM3NDYzNzhjZTQ3Nzg3NTljYzg4NGE="
      - channel=100000
      - uid=123
      - awsAccessKey=AKIA3W5HAAMIUEL5K4OK
      - awsSecretKey=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
    networks:
      - ysc-net
    expose:
      - "80"
    volumes:
      - ./middleware:/var/www/html
  ystemandchess:
    image: ystemandchess
    container_name: ystemandchess
    environment:
      - agora:appID=6c368b93b82a4b3e9fb8e57da830f2a4
      - urls:middlewareURL=localhost/middleware
      - urls:chessClientURL=localhost/chessclient
      - urls:stockFishURL=localhost/stockfishserver
      - urls:chessServerURL=localhost/chessserver
    networks:
      - ysc-net
    expose:
      - "80"
    depends_on:
      - middleware
      - stockfishserver
      - chessclient
      - chessserver
    volumes:
      - ./YStemAndChess/dist/YStemAndChess:/usr/share/nginx/html/